In [1]:
from models.AdvancedModel import *

model = AdvancedModel.create("data/preprocessed/tokenizers/top10k.joblib", 1, 3, 5000000)

In [2]:
train_df = pd.read_csv("data/preprocessed/splits/train.csv")
train_df.head(3)

,id,domain,type,url,content,title,is_reliable
0,1033553.0,beforeitsnews.com,fake,http://beforeitsnews.com/media/2011/10/liberal...,liberal 'ethicists' line up angrily against cn...,liberal 'ethicists' line up angrily against cn...,0
1,3381445.0,dailykos.com,political,https://www.dailykos.com/stories/2014/10/13/13...,hey! good evening! this evening's music featu...,the evening blues,1
2,3989370.0,thinkprogress.org,political,https://thinkprogress.org/7-reasons-north-caro...,in the crowded north carolina primary race for...,<NUM> reasons north carolina’s ‘establishment ...,1

In [3]:
model.fit(train_df['content'], train_df['is_reliable'])

Tokenizing content...

100%|██████████| 634696/634696 [04:23<00:00, 2412.83it/s]
c:\Users\andre\KU\GDS\GDS2026\.venv\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

Fitting vectorizer...
Fitting model...
Fitting complete.

In [4]:
val_df = pd.read_csv("data/preprocessed/splits/val.csv")
val_df.head(3)

,id,domain,type,url,content,title,is_reliable
0,4927322.0,pravda.ru,bias,https://www.pravda.ru/accidents/03-10-2010/105...,"столичные ""зебры"" опасны для детей минувшее во...","столичные ""зебры"" опасны для детей",0
1,7123143.0,americablog.com,bias,http://americablog.com/2009/01/obama-signs-ord...,why does barack obama love the constitution? t...,obama signs order to close guantanamo in a year,0
2,9836763.0,nytimes.com,reliable,https://www.nytimes.com/2017/04/24/us/politics...,"hoping to pad the report card, he announced su...",trump wants it known: grading <NUM> days is ‘r...,1

In [ ]:
from sklearn.metrics import f1_score

print(f"F1-score: {f1_score(val_df['is_reliable'], model.predict(val_df['content']))}")

Tokenizing content...

100%|██████████| 79337/79337 [00:50<00:00, 1573.54it/s]

F1-score: 0.9044072239656193

In [ ]:
model.save("data/models/advanced", 1)